---
title: 'Faux & Friends: A Fake News Detection and Analysis Service'
author: "Allen Chen, Ram Mukund Kripa"
date: "8/4/2020"
output: html_document
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Packages used in this Project

```{r packages, include = FALSE}
library(tidyverse)
library(hoaxy)
library(rtweet)
library(tidytext)
library(here)
library(shiny)
library(text2vec)
```

```{r vectormodel, include = FALSE}

training_path <-  here("training","training_set.csv")
training_set <- read_csv(training_path)

token_train <- itoken(training_set$text,
                     preprocessor = tolower,
                     tokenizer = word_tokenizer,
                     ids = training_set$unique_id)
t_vocab <- create_vocabulary(token_train)
t_vectorizer <- vocab_vectorizer(t_vocab)
dtm_train <- create_dtm(token_train, t_vectorizer)
dim(dtm_train)

library(glmnet)
NFOLDS = 4
glmnet_classifier = cv.glmnet(x = dtm_train, y = training_set[['Class']], 
                              family = 'binomial', 
                              # L1 penalty
                              alpha = 1,
                              # interested in the area under ROC curve
                              type.measure = "auc",
                              # 5-fold cross-validation
                              nfolds = NFOLDS,
                              # high value is less accurate, but has faster training
                              thresh = 1e-3,
                              # again lower number of iterations for faster training
                              maxit = 1e3)

plot(glmnet_classifier)
#print(paste("max AUC =", round(max(glmnet_classifier$cvm), 4)))

#preds <- predict(glmnet_classifier, newx = dtm_train, type #= 'response')[,1]
#glmnet:::auc(training_set$Class, preds)

```

# Interactive Environment

Is your friend spreading COVID misinformation?
Find out now!

## Please Enter a Twitter Handle

```{r input_handle}
inputPanel(
  textInput("input_name", label = "Twitter Username",
              value = "realDonaldTrump")
)

```

### Most Common Words in Recent Tweets

```{r plot}

renderPlot({
  user_dat <- get_timeline(user = input$input_name,
                           n = 3200
                           )
  user_clean <- user_dat %>%
    mutate(text = sub("http.*", "", text) ) %>%
    unnest_tokens(output = "tweet_words",
                  input = text,
                  token = "words") %>%
    select(screen_name,created_at,tweet_words) %>%
    anti_join(stop_words, by = c("tweet_words" = "word")) %>%
    filter(tweet_words!="amp",
           tweet_words!=tolower(input$input_name))
    #%>%
    #mutate(tweet_words = SnowballC::wordStem(tweet_words))
  
  user_clean %>%
    group_by(tweet_words) %>%
    summarize(count = n()) %>%
    arrange(-count) %>%
    head(n = 6L) %>%
    ggplot(mapping = aes(x = reorder(tweet_words,count),
                         y = count))+
      geom_col()+
      coord_flip()+
      labs(title = glue::glue("Most Common Words for ",input$input_name),
           x = "Word Stem",
           y = "Number of Occurences")
  
})
```

### Is this Account Fake News?

```{r testnetmod}
renderPlot({
#test2 <- get_timeline(user = "BreitbartNews",
#                          n = 3200
#                         )
  user_dat <- get_timeline(user = input$input_name,
                           n = 3200
                           )
test_data <- user_dat
test_set <- test_data %>%
  mutate(text = tolower(text)) %>%
  filter(str_detect(string = text,
                    pattern = str_c("covid","corona","china","virus","pandemic","fauci","cdc",sep="|")
                    )) %>%
  select(status_id,text) %>%
  rename("unique_id"="status_id") %>%
  mutate(text = sub("http.*", "", text) )

it_test <- word_tokenizer(test_set$text) %>%
itoken(ids = test_set$unique_id, 
                 # turn off progressbar because it won't look nice in rmd
                 progressbar = FALSE)

dtm_test <- create_dtm(it_test, t_vectorizer)

preds <- predict(glmnet_classifier, dtm_test, type = 'response')
#glmnet:::auc(test$sentiment, preds)

test_result <- ifelse(test = any(preds<0.5),
       yes = "Fake",
       no = "Real")
#plot(glmnet_classifier)

plot(preds)

})

```
